name: linting, testing, building
run-name: ${{ github.actor }} react-project go tests
on: 
  push:
    branches: [master]
  pull_request: 
    branches: [master]
jobs:
  pipeline:
    runs-on: windows-2019
    strategy:
      matrix:
        node-version: [ 17.x ]
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: unit testing
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build
      - name: screenshot testing
        if: always()
        id: screenshots
        run: npm run test:ui:ci
      - name: after
        if: ${{ failure() && steps.screenshots.conclusion == 'failure'}}
        run: /
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f .loki/difference
          git add .
          git checkout -b 'save-screenshots'
          git commit -am 'screenshot failures'
          git push -f origin save-screenshots
